spring:
  r2dbc:
    url: "r2dbc:mssql://spring-reactive.local"
    username: "sa"
    password: "someStrong(!)Password"
  flyway:
    url: "jdbc:sqlserver://spring-reactive.local"
    user: "sa"
    password: "someStrong(!)Password"
